# Generated by Django 4.0.3 on 2022-03-26 07:47

import colorfield.fields
import django.core.validators
from django.db import migrations, models
import savings.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_incoming_rename_category_incomingcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(2), savings.common.validators.validate_only_letters])),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None)),
            ],
        ),
        migrations.AlterField(
            model_name='incomingcategory',
            name='name',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(2), savings.common.validators.validate_only_letters]),
        ),
    ]
