# Generated by Django 4.0.3 on 2022-03-26 08:22

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import savings.common.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_expensecategory_alter_incomingcategory_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), savings.common.validators.validate_only_letters])),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('date', models.DateField(default=datetime.date(2022, 3, 26))),
                ('type', models.CharField(choices=[('Ordinary', 'Ordinary'), ('Extraordinary', 'Extraordinary')], max_length=13)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.expensecategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
