# Generated by Django 4.0.3 on 2022-03-26 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='name',
        ),
        migrations.RemoveField(
            model_name='incoming',
            name='name',
        ),
    ]
