# Generated by Django 4.0.3 on 2022-03-28 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_expense_name_remove_incoming_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.date(2022, 3, 28)),
        ),
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[('ordinary', 'ordinary'), ('extraordinary', 'extraordinary')], max_length=13),
        ),
        migrations.AlterField(
            model_name='incoming',
            name='date',
            field=models.DateField(default=datetime.date(2022, 3, 28)),
        ),
    ]
