# Generated by Django 4.0.3 on 2022-04-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_aboutcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcontent',
            name='author',
            field=models.CharField(default=super, max_length=25),
            preserve_default=False,
        ),
    ]
