# Generated by Django 4.0.3 on 2022-04-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_aboutcontent_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcontent',
            name='author',
            field=models.CharField(default='Super', max_length=25),
        ),
    ]
