# Generated by Django 4.0.3 on 2022-04-09 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_aboutcontent_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutContent',
        ),
    ]
